spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        generate_statistics: false
        order_updates: true
        jdbc:
          batch_size: 100
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: semperante
    password: Sadmin
    url: "jdbc:postgresql://localhost/learn_db?reWriteBatchedInserts=true"
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 100MB
springdoc:
  api-docs:
    enabled: true
    path: /api-docs-op
  swagger-ui:
    path: /api-docs
    operationsSorter: method
server:
  error:
    include-message: always
    include-stacktrace: never
  tomcat:
    max-swallow-size: -1
